# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "ac6360f6fc1895cbd218246f12a771f63d0e5e4f";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "ac6360f6fc1895cbd218246f12a771f63d0e5e4f";
      fetchSubmodules = false;
      sha256 = "sha256-lWqFsucmu6tyLJd4JbNxbBPDRcArQ2KaSUeaqFH73cA=";
    };
    date = "2025-05-17";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "6f88dff82b786e879b255a8e1523547c4f62d031";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "6f88dff82b786e879b255a8e1523547c4f62d031";
      fetchSubmodules = false;
      sha256 = "sha256-0BRHE7O3rcgLa6wg8GVPu9R0MDsA87D6jGbA7bHZ7N0=";
    };
    date = "2025-05-18";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v1.1.1";
    src = fetchgit {
      url = "https://github.com/rifsxd/KernelSU-Next.git";
      rev = "v1.1.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-h99YriWugjS4AuAJzMFm2AN+1Dt1BigooKUYMzVCXL4=";
    };
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "12851";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-b1Y1A182rVALT8S7eBa7cu9VlOG8rkT6B0xemI/EwP4=";
    };
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "v0.9.5";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "v0.9.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pvaL6KEB7X3s8zyLQSPhBhoXaNdVDthH7HnAZRE9JYk=";
    };
  };
  kernelsu-stable-revision-code = {
    pname = "kernelsu-stable-revision-code";
    version = "11872";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-b1Y1A182rVALT8S7eBa7cu9VlOG8rkT6B0xemI/EwP4=";
    };
  };
  linux-amazon-karnak = {
    pname = "linux-amazon-karnak";
    version = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
    src = fetchFromGitHub {
      owner = "mt8163";
      repo = "android_kernel_amazon_karnak_4.9";
      rev = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
      fetchSubmodules = false;
      sha256 = "sha256-viqlQBPd2SuiAphFKiwjtckC3gDTGkbLv2dgZKMP3Oc=";
    };
    date = "2023-10-09";
  };
  linux-moto-rtwo-lineageos-21 = {
    pname = "linux-moto-rtwo-lineageos-21";
    version = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
      fetchSubmodules = false;
      sha256 = "sha256-ZK/DH5N5LdkLe48cANESjw1x74aXoZLFoMAwEDvzEk4=";
    };
    date = "2024-12-21";
  };
  linux-moto-rtwo-lineageos-22_1 = {
    pname = "linux-moto-rtwo-lineageos-22_1";
    version = "e12cc3a36c10596aced0e84a0e08072161c45f63";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "e12cc3a36c10596aced0e84a0e08072161c45f63";
      fetchSubmodules = false;
      sha256 = "sha256-KZSIus0Ws7FM4O9zyxmdPvGcYsXv/rubwnOuwgo7yHw=";
    };
    date = "2025-03-28";
  };
  linux-oneplus-13 = {
    pname = "linux-oneplus-13";
    version = "9920459dfb0080dd8a81c41d95701483857f804a";
    src = fetchFromGitHub {
      owner = "OnePlusOSS";
      repo = "android_kernel_common_oneplus_sm8750";
      rev = "9920459dfb0080dd8a81c41d95701483857f804a";
      fetchSubmodules = false;
      sha256 = "sha256-EDX16/0QWSdC70sAyuNFTdQ9sNreXdvJRAmZvBLsXq8=";
    };
    date = "2025-08-30";
  };
  linux-oneplus-8t-blu-spark = {
    pname = "linux-oneplus-8t-blu-spark";
    version = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
    src = fetchFromGitHub {
      owner = "engstk";
      repo = "op8";
      rev = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
      fetchSubmodules = false;
      sha256 = "sha256-KWLtY7KWhHmk6LVYpvIz6XT93+yjteex/250crk9Lxw=";
    };
    date = "2024-12-26";
  };
  oneplus-13-sched-ext = {
    pname = "oneplus-13-sched-ext";
    version = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
    src = fetchFromGitHub {
      owner = "HanKuCha";
      repo = "sched_ext";
      rev = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
      fetchSubmodules = false;
      sha256 = "sha256-GamqRqQDjssYudTAfpwXuVbdEZfwWVOLBipagn9WkHw=";
    };
    date = "2025-06-14";
  };
  sukisu = {
    pname = "sukisu";
    version = "8db55f56a9ec59e1b0942b486463aa390a6bbf8e";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "8db55f56a9ec59e1b0942b486463aa390a6bbf8e";
      fetchSubmodules = false;
      sha256 = "sha256-feBabLJ99bDm7a985fUlbGfRnGdCZ1vLXub3Uc1HoAc=";
    };
    date = "2025-10-17";
  };
  sukisu-nongki = {
    pname = "sukisu-nongki";
    version = "2fdb933accb4de98dd7e9bb0ded64d73a8176b8a";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "2fdb933accb4de98dd7e9bb0ded64d73a8176b8a";
      fetchSubmodules = false;
      sha256 = "sha256-mW9D5nI39i6tMhBScChrxYdL4bPpJKmJgrRZtLWknIM=";
    };
    date = "2025-10-08";
  };
  sukisu-patch = {
    pname = "sukisu-patch";
    version = "f9a759905ab257e9bc287cd72e46f233c132ea7a";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU_patch";
      rev = "f9a759905ab257e9bc287cd72e46f233c132ea7a";
      fetchSubmodules = false;
      sha256 = "sha256-Vw9EP8H7czIFDB1P3eOMIb1+kAWhAIaEMzRDLBldTmo=";
    };
    date = "2025-09-28";
  };
  sukisu-revision-code = {
    pname = "sukisu-revision-code";
    version = "13375";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-b1Y1A182rVALT8S7eBa7cu9VlOG8rkT6B0xemI/EwP4=";
    };
  };
  sukisu-susfs = {
    pname = "sukisu-susfs";
    version = "f2274fab279726399de7f55fcd4f549406fdabe6";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "f2274fab279726399de7f55fcd4f549406fdabe6";
      fetchSubmodules = false;
      sha256 = "sha256-3KJ4FJDu/lSd14aF3+kbVqGfOOCzIIeM3+bAnAoI5Dc=";
    };
    date = "2025-10-18";
  };
  susfs-android13-5_15 = {
    pname = "susfs-android13-5_15";
    version = "054e11f66e09a9859d94e6dd16f3f0f937adf1ba";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "054e11f66e09a9859d94e6dd16f3f0f937adf1ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rBLoXd2Z8+ZY6LEJ+C00FkKUIRH5y/eTUbFdALsX18g=";
    };
    date = "2025-10-17";
  };
  susfs-android15-6_6 = {
    pname = "susfs-android15-6_6";
    version = "0d3540e7dabc36dee411ac92501f8ab7b1bfa25a";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "0d3540e7dabc36dee411ac92501f8ab7b1bfa25a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X8q61C5XK/s6rNUMtxqBGaUQbKFqfRbiu7AhKnFX8s8=";
    };
    date = "2025-10-17";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "c78589daee1bea2d6235c666e5f676d87d9ab1d9";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "c78589daee1bea2d6235c666e5f676d87d9ab1d9";
      fetchSubmodules = false;
      sha256 = "sha256-05uLz6XsAPjrgwc4nYtISAFY1zNCTnE8mJV1w21XcCI=";
    };
    date = "2025-10-16";
  };
}
