# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  anykernel-kernelsu = {
    pname = "anykernel-kernelsu";
    version = "ac6360f6fc1895cbd218246f12a771f63d0e5e4f";
    src = fetchFromGitHub {
      owner = "Kernel-SU";
      repo = "AnyKernel3";
      rev = "ac6360f6fc1895cbd218246f12a771f63d0e5e4f";
      fetchSubmodules = false;
      sha256 = "sha256-lWqFsucmu6tyLJd4JbNxbBPDRcArQ2KaSUeaqFH73cA=";
    };
    date = "2025-05-17";
  };
  anykernel-osm0sis = {
    pname = "anykernel-osm0sis";
    version = "6f88dff82b786e879b255a8e1523547c4f62d031";
    src = fetchFromGitHub {
      owner = "osm0sis";
      repo = "AnyKernel3";
      rev = "6f88dff82b786e879b255a8e1523547c4f62d031";
      fetchSubmodules = false;
      sha256 = "sha256-0BRHE7O3rcgLa6wg8GVPu9R0MDsA87D6jGbA7bHZ7N0=";
    };
    date = "2025-05-18";
  };
  gcc-aarch64-linux-android = {
    pname = "gcc-aarch64-linux-android";
    version = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
    src = fetchFromGitHub {
      owner = "kindle4jerry";
      repo = "aarch64-linux-android-4.9-bakup";
      rev = "5797d7f622321e734558bd3372a9ab5ad6e6a48e";
      fetchSubmodules = false;
      sha256 = "sha256-ZrQmFyiDOKg+qcgdpZqtz+LgDDaao2W27kdZZ2As8XU=";
    };
    date = "2020-02-22";
  };
  gcc-arm-linux-androideabi = {
    pname = "gcc-arm-linux-androideabi";
    version = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
    src = fetchFromGitHub {
      owner = "KudProject";
      repo = "arm-linux-androideabi-4.9";
      rev = "3ecb542702c2ca0e502533c3f6d02f0f06f584f1";
      fetchSubmodules = false;
      sha256 = "sha256-5aF2Pl+h6J8/5TfQf2ojp3FCnoKakWH6KBCkWdy5ho8=";
    };
    date = "2019-11-25";
  };
  kernelsu-next = {
    pname = "kernelsu-next";
    version = "v1.1.1";
    src = fetchgit {
      url = "https://github.com/rifsxd/KernelSU-Next.git";
      rev = "v1.1.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-h99YriWugjS4AuAJzMFm2AN+1Dt1BigooKUYMzVCXL4=";
    };
  };
  kernelsu-next-revision-code = {
    pname = "kernelsu-next-revision-code";
    version = "12851";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  kernelsu-stable = {
    pname = "kernelsu-stable";
    version = "v0.9.5";
    src = fetchgit {
      url = "https://github.com/tiann/KernelSU.git";
      rev = "v0.9.5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pvaL6KEB7X3s8zyLQSPhBhoXaNdVDthH7HnAZRE9JYk=";
    };
  };
  kernelsu-stable-revision-code = {
    pname = "kernelsu-stable-revision-code";
    version = "11872";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  linux-amazon-karnak = {
    pname = "linux-amazon-karnak";
    version = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
    src = fetchFromGitHub {
      owner = "mt8163";
      repo = "android_kernel_amazon_karnak_4.9";
      rev = "e22c713c7c4f0c8d08267f6bba98b8c4cde8310f";
      fetchSubmodules = false;
      sha256 = "sha256-viqlQBPd2SuiAphFKiwjtckC3gDTGkbLv2dgZKMP3Oc=";
    };
    date = "2023-10-09";
  };
  linux-moto-rtwo-lineageos-21 = {
    pname = "linux-moto-rtwo-lineageos-21";
    version = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "1bdeb4f5c8d2b98ef5f2bedaa5d704032dffd676";
      fetchSubmodules = false;
      sha256 = "sha256-ZK/DH5N5LdkLe48cANESjw1x74aXoZLFoMAwEDvzEk4=";
    };
    date = "2024-12-21";
  };
  linux-moto-rtwo-lineageos-22_1 = {
    pname = "linux-moto-rtwo-lineageos-22_1";
    version = "e12cc3a36c10596aced0e84a0e08072161c45f63";
    src = fetchFromGitHub {
      owner = "LineageOS";
      repo = "android_kernel_motorola_sm8550";
      rev = "e12cc3a36c10596aced0e84a0e08072161c45f63";
      fetchSubmodules = false;
      sha256 = "sha256-KZSIus0Ws7FM4O9zyxmdPvGcYsXv/rubwnOuwgo7yHw=";
    };
    date = "2025-03-28";
  };
  linux-oneplus-13 = {
    pname = "linux-oneplus-13";
    version = "9920459dfb0080dd8a81c41d95701483857f804a";
    src = fetchFromGitHub {
      owner = "OnePlusOSS";
      repo = "android_kernel_common_oneplus_sm8750";
      rev = "9920459dfb0080dd8a81c41d95701483857f804a";
      fetchSubmodules = false;
      sha256 = "sha256-EDX16/0QWSdC70sAyuNFTdQ9sNreXdvJRAmZvBLsXq8=";
    };
    date = "2025-08-30";
  };
  linux-oneplus-8t-blu-spark = {
    pname = "linux-oneplus-8t-blu-spark";
    version = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
    src = fetchFromGitHub {
      owner = "engstk";
      repo = "op8";
      rev = "64c109e3f3ba97fa7aed730ab7b4238b91df028b";
      fetchSubmodules = false;
      sha256 = "sha256-KWLtY7KWhHmk6LVYpvIz6XT93+yjteex/250crk9Lxw=";
    };
    date = "2024-12-26";
  };
  oneplus-13-sched-ext = {
    pname = "oneplus-13-sched-ext";
    version = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
    src = fetchFromGitHub {
      owner = "HanKuCha";
      repo = "sched_ext";
      rev = "7ab1d04d5cb622d6c32c932add617803074ec5a7";
      fetchSubmodules = false;
      sha256 = "sha256-GamqRqQDjssYudTAfpwXuVbdEZfwWVOLBipagn9WkHw=";
    };
    date = "2025-06-14";
  };
  sukisu = {
    pname = "sukisu";
    version = "d4dcf610c936a2e7d00fdc170a1f13ed4936f6c4";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "d4dcf610c936a2e7d00fdc170a1f13ed4936f6c4";
      fetchSubmodules = false;
      sha256 = "sha256-cN4/xX+vqHMVYj8Txtd6ClqfdXpOiKtxNXqTwOnSYek=";
    };
    date = "2025-10-01";
  };
  sukisu-nongki = {
    pname = "sukisu-nongki";
    version = "3f4293e69a24ef51f4c1e99e73f536483b4f8f38";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "3f4293e69a24ef51f4c1e99e73f536483b4f8f38";
      fetchSubmodules = false;
      sha256 = "sha256-FIJSf2KQ7Ggt2gZqawG6ct0X7DB+oW0AKw8co7EdiLc=";
    };
    date = "2025-10-02";
  };
  sukisu-patch = {
    pname = "sukisu-patch";
    version = "f9a759905ab257e9bc287cd72e46f233c132ea7a";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU_patch";
      rev = "f9a759905ab257e9bc287cd72e46f233c132ea7a";
      fetchSubmodules = false;
      sha256 = "sha256-Vw9EP8H7czIFDB1P3eOMIb1+kAWhAIaEMzRDLBldTmo=";
    };
    date = "2025-09-28";
  };
  sukisu-revision-code = {
    pname = "sukisu-revision-code";
    version = "13375";
    src = fetchurl {
      url = "https://example.com";
      sha256 = "sha256-6o+sfGX7WJsNU1YPUlH3T56bJDR43Laz6nm142RJyNk=";
    };
  };
  sukisu-susfs = {
    pname = "sukisu-susfs";
    version = "8650a9ad57521953f5be48bf4742eb08e1a8af07";
    src = fetchFromGitHub {
      owner = "SukiSU-Ultra";
      repo = "SukiSU-Ultra";
      rev = "8650a9ad57521953f5be48bf4742eb08e1a8af07";
      fetchSubmodules = false;
      sha256 = "sha256-ibVZQhykQlQyGGD7GBTzMWVuQnXJThGivWhwFf/8qqM=";
    };
    date = "2025-10-01";
  };
  susfs-android13-5_15 = {
    pname = "susfs-android13-5_15";
    version = "64446fa69ffdb95344874dd0d04bec11caf457a5";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "64446fa69ffdb95344874dd0d04bec11caf457a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-WloWEL+jQ94VwROu6yKx9Z/I38AHa8KFrEVCf/5h9x0=";
    };
    date = "2025-10-02";
  };
  susfs-android15-6_6 = {
    pname = "susfs-android15-6_6";
    version = "1d41a16950595f86b821e3024c4c313c619cb402";
    src = fetchgit {
      url = "https://gitlab.com/simonpunk/susfs4ksu.git";
      rev = "1d41a16950595f86b821e3024c4c313c619cb402";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6NKEFBhh3iuP8iDLf4xdIPeewn+lztP9k0wvYKcM2XU=";
    };
    date = "2025-09-30";
  };
  wildplus-kernel-patches = {
    pname = "wildplus-kernel-patches";
    version = "59df7ce07a7ad5e35cce65f0e42022ab4cd3f0cf";
    src = fetchFromGitHub {
      owner = "WildPlusKernel";
      repo = "kernel_patches";
      rev = "59df7ce07a7ad5e35cce65f0e42022ab4cd3f0cf";
      fetchSubmodules = false;
      sha256 = "sha256-E1I2ulABl09xNMWjWw4iaIL4jT0pC4d7LliRJBI+a9M=";
    };
    date = "2025-10-03";
  };
}
